@startuml

skinparam packageStyle rect

package bouquet #lightgreen {
    package "Action" { }
    package "Actor" { }
    package "Bin" { }
    package "Micro Service" { }
    package "Scenario" { }
    package "Sub System" { }
    package "Test" { }
    package "Use Case" { }
}

package sails #lightblue {
    folder "api" #dddddd {
        package "controllers" {
        }
        package "models" { }
    }
    folder "bin" #dddddd {
    }
    folder "docs" #dddddd {
    }
    folder "deploy" #dddddd {
        package "uservices" { }
    }
    folder "test" #dddddd {
    }
    folder "views" #dddddd {
    }
}

Action ..> controllers
Action ..> bin
Actor ..> controllers
Actor ..> test
Actor ..> docs
Actor ..> bin
Actor ..> views
Bin ..> bin
"Micro Service" ..> uservices
"Micro Service" ..> docs
Scenario ..> docs
Scenario ..> test
"Sub System" ..> docs
Test ..> test
"Use Case" ..> docs
"Use Case" ..> test
bin --> controllers
views --> controllers

@enduml

