@startuml

package  "<%= nameSpaces %>"  #lightblue {
  folder bin #ffffff {
    file binName
  }

  folder Services #ffffff {
    file uservice
  }

  node micro

  node sailsjs
  database DB1

  sailsjs -- DB1
  bin .. sailsjs
  Services .. micro

  micro -- DB1
  sailsjs -> micro
}

@enduml
