@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "<%= nameSpaces %>" #lightblue {

    interface "<%= nameSpaces %>" {
    }

    CLI ()-- "<%= nameSpaces %>"
    REST ()-- "<%= nameSpaces %>"
    Web ()-- "<%= nameSpaces %>"
}

User --> "<%= nameSpaces %>"
"<%= nameSpaces %>" --> Used

@enduml
