@startuml
  rectangle "Physical Diagram TBD"
@enduml

package "<%= nameSpaces %>" #lightblue {
  interface CLI
  interface Web
  interface REST
  folder bin #ffffff {
    component binName
  }

  folder appName #ffffff {
    component sails.io
    component sailsjs
  }

  folder uService1 #ffffff {
    component micro
  }
}

CLI -- binName
binName --  REST

Web -- sailsjs
Web -- REST
REST -- sailsjs
Web -- sails.io
REST -- micro

