@startuml
  rectangle "UseCase Diagram TBD"
@enduml

left to right direction

actor :User: <<Person>>
actor :SubSystem: <<Person>>


rectangle "<%= nameSpaces %>" #lightBlue {
UseCase UC1  as "Use Case1"
UseCase UC2  as "Use Case2"


User --> UC1
UC1 --> UC2
UC2 --> SubSystem
}

