@startuml

package deploy {
    package test {
      class "deployment-file"
    }
    package dev {
      class "deployment-file "
    }
    package production {
      class " deployment-file "
    }
    package uservices {
      package NewService {
        class "Dockerfile"
        class "package-json"
        class "index-js"
      }
    }
}
@enduml

