@startuml

rectangle parameters $lightgreen {
    rectangle controller
    rectangle action
    controller .. action
}

rectangle Action #lightblue {
    folder bin  #white {
      artifact "<controller>-<action>"

    }

    folder controllers #white  {
      folder "<controller>" #lightgreen {
          artifact "action.js"
      }
    }

    folder test #white  {
      folder "bin" as b #lightgreen {
        artifact "<controller>-<action>-Bin-Test.js"
      }
      folder integration  #lightgreen {
        artifact "<controller>-<action>-Test.js"
      }
    }
  bin .. controllers
  controllers .. test
}


@enduml
