@startuml

rectangle parameters #lightgreen {
    rectangle Name
}

rectangle "SubSystem" #lightblue {
    folder docs #white {
      folder UseCases #lightgreen {
        folder <Name> #white {
          artifact Activities.puml
          artifact index.rst
        }
      }
    }

    folder test #white {
      folder UseCases as ts #lightblue {
        artifact "<Name>-test.js" #white
      }
    }
    test .. docs
}

@enduml

