#!/usr/bin/env node

var program =  require('commander');

program
  .version("0.0.1")
  <% _.each(usecases, function(usecase) %>
  # .command('command <argment>', '<%= usecase %>')
  <% }); %>
  .parse(process.argv);
