@startuml
  rectangle "Physical TBD"
@enduml
interface external

package "<%= name %>" #lightblue {
    component service
    interface internal
}
external -- service : 3000
internal - service : 5000
@enduml
