@startuml

partition "<%= name %>" {

}

partition User  #cccccc {
  (*) --> "Create Project"
  --> "Write Code"
}

partition "<%= name %>" #lightblue {
  "Write Code" --> "Test Code"
  "Test Code" --> "Deploy Code"
  "Deploy Code" --> (*)
}

partition Used  #cccccc {
}
@enduml
