@startuml

partition "<%= name %>" {

}

partition SubSystem  #cccccc {
  (*) --> "Create Project"
  --> "Write Code"
}

partition "<%= name %>" {
  "Write Code" --> "Test Code"
  "Test Code" --> "Deploy Code"
  "Deploy Code" --> (*)
}

@enduml
