@startuml

skinparam packageStyle rect

package bouquet #lightgray {
    package "Action" #lightgreen {
    }
    package "Actor" #lightblue {
    }
    package "Bin" #lightgreen {
    }
    package "Micro-Service" #lightgreen {
    }
    package "SubSystem" #lightblue {
    }
    package "Test" #lightgreen {
    }
    package "UseCase" #lightblue {
    }
    package "Scenario" #lightblue {
    }
}

@enduml

