@startuml

left to right direction

<%
var i = 0;
_.each(actors, function(actor) {
i++;
%>
:actor.name: as A<%= i %>
<% } %>

:Actor Name: as A1

rectangle "<%= name %>"  #aaffff {
<%
var j = 0;
_.each(usecases, function(usecase) {
j++;
%>
(usecase.name) as U<%= j %>
<% } %>
}


@enduml
